### ISSUE TITLE
Include "Include Document Outline" button in menu bar

### ISSUE THREAD

**Issue by dtu-compute** [dtu-compute/dtu-enote-pdfjs#1]
Include "Include Document Outline" button in menu bar.

On the screenshot below it is the second button from the left.

![4](https://cloud.githubusercontent.com/assets/13518486/22594277/b5d9853c-ea22-11e6-8ffd-52d036b8fe2c.png)

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by iainbryson** [comment]
To be clear on this: The document outline is not in the main view by default.  It's in the sidebar view, which is activated by pressing on the sidebar button (the one in the middle of your screenshot) and can be dismissed by clicking on it again?

Do you want me to enable the sidebar view as it is, or fix the sidebar into the "on" position?

![image](https://user-images.githubusercontent.com/1531103/27507242-db16d304-58c2-11e7-8ff4-02f85d27f2ee.png)

**Comment by dtu-compute** [comment]
Yes, that's the one.

So far it is only the statistics courses that have requested this feature, so we better have it off by default. I wouldn't be surprised though if everyone wants it on by default later on.

They would like that the second button on your screenshot is the default.
